name: instagram_flutter
description: Full Stack Instagram Clone

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_storage: ^10.2.16
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  firebase_core: ^1.17.0
  flutter_svg: ^1.1.0
  image_picker: ^0.8.5+3
  provider: ^6.0.3
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/ic_instagram.svg